"use client";

import {useCallback,useEffect,useMemo,useState} from "react";

type ManualEvent={shareholder:string;pledgee:string;amountText:string;pledgeDate:string};
type ReviewItem={id:number;announcementId:string;reason:string;payload:string;status:string;stockCode:string;stockName:string;title:string;announceDate:string;reportDate:string;pdfUrl?:string;archivedPdfUrl?:string;parseStatus:string;parseAttempts:number;lastError?:string;existingEvents?:ManualEvent[]};
type ReviewPayload={date:string;status:string;counts:{pending?:number;approved?:number;rejected?:number};data:ReviewItem[];generatedAt:string;error?:string};
const blankEvent=():ManualEvent=>({shareholder:"",pledgee:"",amountText:"",pledgeDate:""});
const strings=(value:unknown)=>String(value??"").trim();
const isNewPledge=(value:unknown)=>!strings(value)||strings(value)==="新增质押";

function candidates(item:ReviewItem):ManualEvent[]{
  if(item.existingEvents?.length)return item.existingEvents.map(row=>({...blankEvent(),...row}));
  try{
    const payload=JSON.parse(item.payload||"{}") as Record<string,unknown>;
    const source=Array.isArray(payload.candidates)?payload.candidates:[payload];
    const rows=source.map(value=>value as Record<string,unknown>)
      .filter(row=>isNewPledge(row.type))
      .map(row=>({shareholder:strings(row.shareholder),pledgee:strings(row.pledgee),amountText:strings(row.amountText||row.pledge_amount),pledgeDate:strings(row.pledgeDate||row.startDate||row.start_date)}))
      .filter(row=>row.shareholder||row.pledgee||row.amountText||row.pledgeDate);
    return rows.length?rows:[blankEvent()];
  }catch{return [blankEvent()];}
}

export default function ReviewWorkbench({initialDate}:{initialDate:string}){
  const [date,setDate]=useState(initialDate);const [payload,setPayload]=useState<ReviewPayload|null>(null);const [selectedId,setSelectedId]=useState<number|null>(null);const [drafts,setDrafts]=useState<Record<number,ManualEvent[]>>({});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [search,setSearch]=useState("");
  const load=useCallback(async(targetDate=date)=>{setLoading(true);setError("");try{const query=new URLSearchParams({status:"pending"});if(targetDate)query.set("date",targetDate);const response=await fetch(`/api/reviews?${query}`,{cache:"no-store"});const body=await response.json() as ReviewPayload;if(response.status===403)throw new Error("unauthorized");if(!response.ok)throw new Error(body.error||"审核队列读取失败");setPayload(body);setDate(body.date);setSelectedId(current=>body.data.some(row=>row.id===current)?current:body.data[0]?.id||null);setDrafts(current=>{const next={...current};for(const item of body.data)if(!next[item.id])next[item.id]=candidates(item);return next;});}catch(reason){setError(reason instanceof Error?reason.message:"审核队列读取失败");}finally{setLoading(false);}},[date]);
  useEffect(()=>{void load(initialDate);},[]);// eslint-disable-line react-hooks/exhaustive-deps
  const rows=useMemo(()=>{const keyword=search.trim().toLowerCase();return (payload?.data||[]).filter(row=>!keyword||`${row.stockCode}${row.stockName}${row.title}${row.reason}`.toLowerCase().includes(keyword));},[payload,search]);
  const selected=(payload?.data||[]).find(row=>row.id===selectedId)||null;const events=selectedId?drafts[selectedId]||[blankEvent()]:[];
  const setEvents=(next:ManualEvent[])=>selectedId&&setDrafts(current=>({...current,[selectedId]:next}));
  const updateEvent=(index:number,key:keyof ManualEvent,value:string)=>setEvents(events.map((row,rowIndex)=>rowIndex===index?{...row,[key]:value}:row));
  const moveNext=()=>{const index=rows.findIndex(row=>row.id===selectedId);setSelectedId(rows[index+1]?.id||rows[index-1]?.id||null);};
  const submit=async(action:"approve"|"reject"|"requeue")=>{if(!selected)return;setSaving(true);setError("");setMessage("");try{const resolution=action==="approve"?`人工逐页核验通过，共 ${events.length} 条新增质押`:action==="reject"?"人工核验：不属于新增质押":"人工要求重新执行规则解析";const response=await fetch(`/api/reviews/${selected.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,resolution,events})});const body=await response.json() as {error?:string;closing?:{status?:string};warnings?:string[]};if(!response.ok)throw new Error(body.error||"保存失败");const warningNote=body.warnings?.length?`；已按人工结论入库，并记录 ${body.warnings.length} 项质量提示`:"";setMessage(action==="approve"?`已确认 ${selected.stockName}${warningNote}；${body.closing?.status==="published"?"当日日报已自动升级最终版":"继续处理下一份"}`:action==="reject"?`已排除 ${selected.stockName}`:`${selected.stockName} 已重新进入规则解析`);moveNext();await load(payload?.date||date);}catch(reason){setError(reason instanceof Error?reason.message:"保存失败");}finally{setSaving(false);}};
  useEffect(()=>{const listener=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key==="Enter"&&selected&&!saving){event.preventDefault();void submit("approve");}if(event.altKey&&event.key==="ArrowDown"){event.preventDefault();moveNext();}};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener);});
  if(error==="unauthorized")return <main className="reviewGate"><div><span>HBF REVIEW DESK</span><h1>新增质押人工审核台</h1><p>审核操作会写入审计日志并影响正式日报，需要先使用获授权的账户登录。</p><a href={`/signin-with-chatgpt?return_to=${encodeURIComponent(`/review${date?`?date=${date}`:""}`)}`}>登录审核后台</a><a className="secondary" href="/">返回日报</a></div></main>;
  return <main className="reviewPage"><header className="reviewHeader"><a href="/"><span>HBF</span><b>新增质押审核台<small>MANUAL REVIEW DESK</small></b></a><div><label>报告日期<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><button onClick={()=>void load(date)} disabled={loading}>读取队列</button><a href={`/report/${date}`}>查看日报 ↗</a></div></header>
    <section className="reviewSummary"><div><span>待审核</span><strong>{payload?.counts.pending||0}</strong></div><div><span>已人工通过</span><strong>{payload?.counts.approved||0}</strong></div><div><span>已排除</span><strong>{payload?.counts.rejected||0}</strong></div><p>仅核对并入库新增质押。解除、再质押、补充质押与展期全部排除。<kbd>Ctrl</kbd>+<kbd>Enter</kbd>确认，<kbd>Alt</kbd>+<kbd>↓</kbd>下一份。</p></section>
    {message&&<div className="reviewNotice success">{message}</div>}{error&&<div className="reviewNotice error">{error}</div>}
    <div className="reviewWorkspace"><aside className="reviewQueue"><div className="reviewQueueHead"><b>{date} 未决公告</b><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="搜索股票或标题"/></div>{loading?<div className="reviewState">正在读取…</div>:rows.map((row,index)=><button key={row.id} className={row.id===selectedId?"active":""} onClick={()=>setSelectedId(row.id)}><i>{index+1}</i><span><b>{row.stockName}<small>{row.stockCode}</small></b><em>{row.title}</em><small>{row.reason}</small></span><strong>{row.parseAttempts}次</strong></button>)}{!loading&&!rows.length&&<div className="reviewState">该日期待审核队列已清零。</div>}</aside>
      <section className="reviewDocument">{selected?<><div className="reviewPaneHead"><div><b>{selected.stockName} {selected.stockCode}</b><span>{selected.title}</span></div><a href={selected.archivedPdfUrl||selected.pdfUrl} target="_blank" rel="noreferrer">新窗口打开PDF ↗</a></div>{selected.archivedPdfUrl?<iframe key={selected.announcementId} title={`${selected.stockName}官方公告`} src={selected.archivedPdfUrl}/>:<div className="reviewPdfFallback"><b>PDF尚未归档</b><p>使用右上角“新窗口打开PDF”核对官方原文。</p></div>}</>:<div className="reviewState">请选择一份待审核公告。</div>}</section>
      <section className="reviewEditor">{selected?<><div className="reviewPaneHead"><div><b>新增质押数据</b><span>{selected.stockName} {selected.stockCode} · 公告 {selected.announcementId}</span></div><button onClick={()=>setEvents([...events,blankEvent()])}>＋新增一行</button></div><div className="reviewAuthority"><b>人工结论优先</b><span>只录入新增质押。解除、再质押、补充质押和展期请直接排除；字段可留空，系统不会阻止提交。</span></div><div className="reviewReason"><b>自动解析提示</b><p>{selected.reason}</p>{selected.lastError&&<code>{selected.lastError}</code>}</div><div className="reviewForms">{events.map((row,index)=><fieldset key={index}><legend>新增质押 {index+1}<button onClick={()=>setEvents(events.filter((_,rowIndex)=>rowIndex!==index))} disabled={events.length===1}>删除</button></legend><label>质押股东<input value={row.shareholder} onChange={event=>updateEvent(index,"shareholder",event.target.value)} placeholder="以人工核对公告结果为准，可留空"/></label><label>质权人<input value={row.pledgee} onChange={event=>updateEvent(index,"pledgee",event.target.value)} placeholder="公告未披露或无法确认时可留空"/></label><div className="reviewFormGrid"><label>质押股票数量<input value={row.amountText} onChange={event=>updateEvent(index,"amountText",event.target.value)} placeholder="如 12,500,000 股；可按原文填写"/></label><label>质押日期<input type="date" value={row.pledgeDate} onChange={event=>updateEvent(index,"pledgeDate",event.target.value)}/></label></div></fieldset>)}</div><div className="reviewActions"><button className="reject" disabled={saving} onClick={()=>void submit("reject")}>非新增质押 / 排除</button><button className="requeue" disabled={saving} onClick={()=>void submit("requeue")}>重新规则解析</button><button className="approve" disabled={saving} onClick={()=>void submit("approve")}>{saving?"正在保存…":`确认新增质押入库（${events.length}条）`}</button></div></>:<div className="reviewState">选择公告后开始审核。</div>}</section>
    </div></main>;
}
