"use client";

import { useEffect, useState } from "react";

type Role="capital"|"financing"|"advisor";
type Form={role:Role;organization:string;contactName:string;email:string;stockCode:string;shareholder:string;amountMin:string;amountMax:string;termMonths:string;preference:string;purpose:string;notes:string;consent:boolean};
const initial:Form={role:"capital",organization:"",contactName:"",email:"",stockCode:"",shareholder:"",amountMin:"",amountMax:"",termMonths:"12",preference:"",purpose:"",notes:"",consent:false};

export default function MatchPage(){
  const [form,setForm]=useState<Form>(initial);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState("");const [result,setResult]=useState<{requestId?:number;message:string}|null>(null);const [total,setTotal]=useState(0);
  useEffect(()=>{void fetch("/api/match-market",{cache:"no-store"}).then((response)=>response.json() as Promise<{data?:{total?:{total?:number}}}>).then((payload)=>setTotal(Number(payload.data?.total?.total||0)));},[]);
  const financing=form.role!=="capital";const update=<K extends keyof Form>(key:K,value:Form[K])=>setForm((current)=>({...current,[key]:value}));
  const valid=Boolean(form.organization.trim()&&form.contactName.trim()&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)&&Number(form.amountMin)>0&&Number(form.amountMax)>=Number(form.amountMin)&&Number(form.termMonths)>0&&form.consent&&(!financing||(/^\d{6}$/.test(form.stockCode)&&form.shareholder.trim())));
  const submit=async()=>{setSubmitting(true);setError("");try{const response=await fetch("/api/match-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,amountMin:Number(form.amountMin),amountMax:Number(form.amountMax),termMonths:Number(form.termMonths)})});const payload=await response.json() as {error?:string;requestId?:number;message?:string};if(!response.ok)throw new Error(payload.error||"提交失败");setResult({requestId:payload.requestId,message:payload.message||"已进入人工核验"});}catch(reason){setError(reason instanceof Error?reason.message:"提交失败");}finally{setSubmitting(false);}};
  return <main className="publicIntelPage matchPage"><header className="publicHeader"><a className="publicBrand" href="/"><span>H</span><b>HBF质押日报<small>每日关账报告与融资撮合</small></b></a><nav><a href="/">今日日报</a><button>撮合服务</button><a href="/match/desk">我的撮合</a></nav></header><div className="publicWrap"><div className="publicBreadcrumb"><a href="/">首页</a><span>/</span><b>融资撮合</b></div>
    <section className="matchHero"><div><p className="eyebrow">VERIFIED FINANCING MATCH</p><h1>让真实项目与真实资金偏好相遇</h1><p>日报确认事实，平台核验主体与需求；只有双方明确有兴趣后，才安排人工对接。</p><div><span>✓ 联系方式默认不公开</span><span>✓ 双方授权后再交换信息</span><span>✓ 不承诺融资结果</span></div></div><aside><span>当前有效需求</span><strong>{total}</strong><small>仅显示匿名统计</small></aside></section>
    <div className="matchLayout"><section className="matchForm publicPanel">{result?<div className="matchSuccess"><span>✓</span><h2>撮合需求已登记</h2><p>{result.message}</p><div><b>需求编号</b><strong>#{result.requestId||"—"}</strong></div><button onClick={()=>{setResult(null);setForm(initial);}}>继续提交</button></div>:<><div className="matchFormHead"><div><h2>提交撮合需求</h2><p>先提交最小必要信息；敏感材料在确认服务关系后再处理。</p></div><span>人工核验</span></div><div className="roleTabs"><button className={form.role==="capital"?"active":""} onClick={()=>update("role","capital")}><b>我是资方</b><small>登记资金偏好</small></button><button className={financing?"active":""} onClick={()=>update("role","financing")}><b>我是融资方 / FA</b><small>登记项目需求</small></button></div>{financing&&<label className="matchRoleSelect"><span>具体身份</span><select value={form.role} onChange={(event)=>update("role",event.target.value as Role)}><option value="financing">上市公司股东 / 融资方</option><option value="advisor">FA / 财务顾问</option></select></label>}
      <div className="matchFields"><label><span>机构 / 主体名称 *</span><input value={form.organization} onChange={(event)=>update("organization",event.target.value)}/></label><label><span>联系人 *</span><input value={form.contactName} onChange={(event)=>update("contactName",event.target.value)}/></label><label className="full"><span>联系邮箱 *</span><input type="email" value={form.email} onChange={(event)=>update("email",event.target.value)} placeholder="name@company.com"/></label>{financing&&<><label><span>股票代码 *</span><input inputMode="numeric" maxLength={6} value={form.stockCode} onChange={(event)=>update("stockCode",event.target.value.replace(/\D/g,""))}/></label><label><span>融资股东 *</span><input value={form.shareholder} onChange={(event)=>update("shareholder",event.target.value)}/></label></>}<label><span>金额下限（万元）*</span><input type="number" min="1" value={form.amountMin} onChange={(event)=>update("amountMin",event.target.value)}/></label><label><span>金额上限（万元）*</span><input type="number" min="1" value={form.amountMax} onChange={(event)=>update("amountMax",event.target.value)}/></label><label><span>期限（月）*</span><input type="number" min="1" max="120" value={form.termMonths} onChange={(event)=>update("termMonths",event.target.value)}/></label><label><span>{financing?"资金用途":"偏好方向"}</span><select value={financing?form.purpose:form.preference} onChange={(event)=>financing?update("purpose",event.target.value):update("preference",event.target.value)}><option value="">请选择</option>{financing?<><option>补充流动资金</option><option>债务置换</option><option>项目投资</option><option>其他合规用途</option></>:<><option>新增质押融资</option><option>存量融资置换</option><option>风险化解</option><option>综合授信</option></>}</select></label><label className="full"><span>补充说明</span><textarea maxLength={1000} value={form.notes} onChange={(event)=>update("notes",event.target.value)} placeholder="请勿填写身份证、账户等敏感信息"/></label></div>
      <label className="matchConsent"><input type="checkbox" checked={form.consent} onChange={(event)=>update("consent",event.target.checked)}/><span>我同意平台保存上述信息用于人工核验和撮合；未经双方确认，不向对方披露联系方式。</span></label>{error&&<p className="matchError">{error}</p>}<button className="matchSubmit" disabled={!valid||submitting} onClick={()=>void submit()}>{submitting?"正在提交…":"提交并进入人工核验"}</button><small className="matchLegal">提交不代表融资获批或形成居间合同，不吸收资金、不代收融资款。</small></>}</section>
      <aside className="matchAside"><section className="publicPanel"><div className="publicPanelHead"><div><h2>业务闭环</h2><p>从情报到对接</p></div></div><ol><li><b>登记真实需求</b><span>统一主体、金额、期限与资金偏好。</span></li><li><b>质押数据核验</b><span>关联正式日报和官方公告证据。</span></li><li><b>人工筛选匹配</b><span>核验身份、准入范围与合作意向。</span></li><li><b>双向授权对接</b><span>双方同意后才交换联系方式。</span></li></ol></section><section className="matchRevenue"><p className="eyebrow">SERVICE MODEL</p><h2>收入来自完成服务</h2><div><span>项目筛选</span><span>标准尽调</span><span>专项顾问</span><span>撮合服务</span></div><p>具体服务边界、费用和合规安排通过单独协议确认。</p></section><section className="matchPrivacy"><b>隐私边界</b><p>机构名称、股东、邮箱和需求内容不进入公开列表。</p></section></aside></div><footer className="publicFooter"><span>平台提供公开信息整理和撮合线索，不构成授信或投资建议。</span><span>HBF质押日报 · 双向授权撮合</span></footer></div></main>;
}
