"use client";

import { useEffect, useMemo, useState } from "react";

type Row={id:number;announcementId:string;code:string;name:string;shareholder:string;pledgee:string;amount:string;ratio:string;total:string;type:string;date:string;pdfUrl?:string};
type Report={date:string;status:string;ready:boolean;announcement:{total:number;pending:number};event:{total:number;companies:number;releases:number;supplemental:number};reconciliation:{complete:boolean;successfulSources:number;requiredSources:number;unresolved:number};events:Row[];methodology:string};
const statuses:Record<string,string>={collecting:"Collecting",reviewing:"Under review",ready_to_close:"Ready to close",provisional:"Provisional report published",published:"Closed and published"};
const eventType=(value:string)=>value.includes("解除")?"Pledge release":value.includes("补充")?"Supplemental pledge":"New pledge";

export default function EnglishIntelligence(){
  const [report,setReport]=useState<Report|null>(null);const [error,setError]=useState("");
  useEffect(()=>{void fetch("/api/daily-report",{cache:"no-store"}).then(async(response)=>{const body=await response.json() as Report&{error?:string};if(!response.ok)throw new Error(body.error||"Report unavailable");setReport(body);}).catch(reason=>setError(reason instanceof Error?reason.message:"Report unavailable"));},[]);
  const rows=report?.events||[];const high=useMemo(()=>rows.filter(row=>Math.max(parseFloat(row.ratio)||0,parseFloat(row.total)||0)>=50).length,[rows]);
  return <main className="internationalPage"><header className="internationalHeader"><a href="/en"><b>HBF Daily Pledge Report</b><span>A-share closing report & financing match</span></a><nav><a className="active" href="/en">Daily report</a><a href="/reports">Archive</a><a href="/match">Financing match</a><a href="https://www.otcfilingwatch.com/" target="_blank" rel="noreferrer">OTC Filing Watch ↗</a><a href="/">中文</a></nav></header>
    <section className="internationalHero"><div><p className="eyebrow">ONE TRADING DAY · ONE VERIFIED CLOSE</p><h1>A-share pledge facts,<br/>closed once a day.</h1><p>We stop accepting new disclosures at 20:00 China Standard Time, reconcile CNINFO with the Shanghai, Shenzhen and Beijing exchanges, resolve every material difference, and publish one image and one PDF from the same dataset.</p><div className="internationalHeroActions"><button onClick={()=>window.print()} disabled={!rows.length}>Print / Save PDF</button><a className="secondary" href="/match">Submit a financing need</a></div></div><aside><span>Latest report</span><strong>{report?.date||"—"}</strong><div><b>{report?.event.total||0}</b><small>pledge events</small></div><div><b>{report?.event.companies||0}</b><small>listed companies</small></div><div><b>{high}</b><small>high-ratio signals</small></div><p>{report?`${statuses[report.status]||report.status} · ${report.reconciliation.successfulSources}/${report.reconciliation.requiredSources} exchanges reconciled`:"Connecting to closing data…"}</p><p className="marketScopeNote">Coverage: Mainland China A shares only. Hong Kong listings are not included in this product.</p></aside></section>
    <section className="internationalMethod"><div><b>20:00 cutoff · 21:00 target</b><span>Disclosures after 20:00 roll into the next calendar-day report; weekend production remains active</span></div><div><b>Three-exchange reconciliation</b><span>SSE, SZSE and BSE checks must complete and unresolved differences must reach zero</span></div><div><b>Business workflow</b><span>Verified facts support private-credit screening and consent-based financing introductions</span></div></section>
    <section className="internationalFeed"><div className="internationalSectionHead"><div><p className="eyebrow">OFFICIAL DAILY LIST</p><h2>{report?.date||"Latest"} pledge events</h2></div><span>{report?.status==="published"?"Official closing version":report?.status==="provisional"?`Provisional · ${report.announcement.pending||0} filings unresolved`:"Not yet labeled complete"}</span></div>{error?<div className="internationalState">{error}</div>:!report?<div className="internationalState">Loading the latest closing report…</div>:rows.length?<div className="internationalEventList">{rows.map(row=><article key={`${row.announcementId}-${row.id}`}><time>{row.date}</time><div><a href={`/en/company/${encodeURIComponent(row.code)}`}><b>{row.name}</b><small>{row.code}</small></a><p>{row.shareholder} → {row.pledgee||"Pledgee not disclosed"}</p></div><span className={row.type.includes("解除")?"release":row.type.includes("补充")?"supplemental":"new"}>{eventType(row.type)}</span><div className="internationalFacts"><b>{row.amount||"—"}</b><small>{row.ratio?`${row.ratio} of holder's shares`:"ratio not disclosed"}</small></div>{row.pdfUrl?<a className="sourceLink" href={row.pdfUrl} target="_blank" rel="noreferrer">Official filing ↗</a>:<small>Source pending</small>}</article>)}</div>:<div className="internationalState">No verified pledge event is available for this report date.</div>}</section>
    <section className="internationalUseCases"><div><p className="eyebrow">PRIVATE CAPITAL WORKFLOW</p><h2>Facts first. Then qualified introductions.</h2></div><article><b>Capital providers</b><p>Register ticket size, tenor and risk preferences without exposing identity publicly.</p></article><article><b>Shareholders & issuers</b><p>Submit a financing need that can be checked against official pledge history.</p></article><article><b>Financial advisers</b><p>Move a qualified project into review, due diligence, negotiation and consent-based contact exchange.</p></article></section>
    <section className="productFamily"><div><p className="eyebrow">INDEPENDENT DATA SYSTEMS</p><h2>Separate products, no operational conflict.</h2><p>HBF Daily Pledge Report and OTC Filing Watch keep independent collection, databases and public experiences. Cross-market research may be packaged commercially without mixing production systems.</p></div><a href="https://www.otcfilingwatch.com/" target="_blank" rel="noreferrer"><span>US OTC DISCLOSURES</span><b>OTC Filing Watch</b><small>Open the independent OTC product ↗</small></a><a href="/match"><span>FINANCING MATCH</span><b>Submit a mandate</b><small>Start confidential manual review →</small></a></section><footer className="internationalFooter"><span>Public disclosures only. Not investment advice or a credit decision.</span><span>HBF Daily Pledge Report · China A shares</span></footer></main>;
}
