"use client";

import { useEffect, useState } from "react";

type BillingStatus={authenticated:boolean;configured:boolean;plan:string;status:string;currentPeriodEnd?:string};
type Plan={id:"free"|"pro"|"team"|"global";name:string;price:string;note:string;features:string[];featured?:boolean};

export default function PricingClient({locale}:{locale:"zh"|"en"}){
  const en=locale==="en";
  const [billing,setBilling]=useState<BillingStatus|null>(null);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState("");
  useEffect(()=>{void fetch("/api/billing/status",{cache:"no-store"}).then(async(response)=>setBilling(await response.json() as BillingStatus)).catch(()=>setError(en?"Billing status is temporarily unavailable.":"订阅状态暂不可用。"));},[en]);
  const plans:Plan[]=[
    {id:"free",name:en?"Open Intelligence":"公开情报版",price:en?"Free":"免费",note:en?"For initial screening":"用于初步筛查",features:en?["Verified event feed","Official filing traceability","Basic company history"]:["已核验即时事件","官方公告追溯","公司基础历史"]},
    {id:"pro",name:en?"Professional":"专业研究版",price:"US$49/mo",note:en?"For analysts and independent advisors":"面向分析师与独立FA",features:en?["Full pledge history","Risk signals and exports","Downloadable research briefs"]:["完整质押历史","风险信号与数据导出","可下载研究简报"],featured:true},
    {id:"team",name:en?"Institutional Team":"机构团队版",price:"US$199/mo",note:en?"For private credit and funds":"面向资方与信贷团队",features:en?["Team research workspace","Enhanced exports","Financing counterparty analysis"]:["团队研究工作台","增强型批量导出","融资交易对手分析"]},
    {id:"global",name:en?"Global Filing Intelligence":"全球披露情报版",price:"US$299/mo",note:en?"A-share pledge + OTC Filing Watch":"A股质押 + OTC Filing Watch",features:en?["All A-share pledge intelligence","OTC filing intelligence bundle","Cross-market research support"]:["全部A股质押情报","OTC公告情报组合","跨市场研究支持"]},
  ];
  const checkout=async(plan:Plan["id"])=>{if(plan==="free")return;setBusy(plan);setError("");try{const response=await fetch("/api/billing/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan,locale})});const body=await response.json() as {url?:string;error?:string};if(response.status===401){window.location.href=`/signin-with-chatgpt?return_to=${encodeURIComponent(en?"/en/pricing":"/pricing")}`;return;}if(!response.ok||!body.url)throw new Error(body.error||"Checkout unavailable");window.location.href=body.url;}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setBusy(null);}};
  const portal=async()=>{setBusy("portal");setError("");try{const response=await fetch("/api/billing/portal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale})});const body=await response.json() as {url?:string;error?:string};if(!response.ok||!body.url)throw new Error(body.error||"Portal unavailable");window.location.href=body.url;}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setBusy(null);}};
  return <main className="internationalPage pricingPage"><header className="internationalHeader"><a href={en?"/en":"/"}><b>Pledge Radar</b><span>{en?"A-share Shareholder Finance Intelligence":"A股股东融资风险情报"}</span></a><nav><a href={en?"/en":"/"}>{en?"Live Intelligence":"即时情报"}</a><a href="https://www.otcfilingwatch.com/" target="_blank" rel="noreferrer">OTC Filing Watch ↗</a><a href={en?"/pricing":"/en/pricing"}>{en?"中文":"English"}</a></nav></header><section className="pricingHero"><p className="eyebrow">INTELLIGENCE SUBSCRIPTIONS</p><h1>{en?"Turn public filings into financing risk decisions":"把公开披露转化为融资风控决策"}</h1><p>{en?"Subscribe to verified A-share pledge intelligence, institutional research workflows, and an optional OTC filing intelligence bundle.":"订阅可追溯的A股质押情报、机构研究工作流，以及可选的 OTC 公告情报组合。"}</p>{billing?.plan&&billing.plan!=="free"&&<div className="billingCurrent">{en?"Current plan":"当前方案"}: <b>{billing.plan.toUpperCase()}</b> · {billing.status}{billing.currentPeriodEnd&&` · ${en?"renews/ends":"周期截止"} ${billing.currentPeriodEnd.slice(0,10)}`}<button onClick={()=>void portal()} disabled={busy==="portal"}>{en?"Manage billing":"管理订阅"}</button></div>}{error&&<div className="billingError">{error}</div>}</section><section className="commercialPricingGrid">{plans.map(plan=><article key={plan.id} className={plan.featured?"featured":""}><span>{plan.name}</span><strong>{plan.price}</strong><small>{plan.note}</small><ul>{plan.features.map(feature=><li key={feature}>✓ {feature}</li>)}</ul>{plan.id==="free"?<a href={en?"/en":"/"}>{en?"Explore live data":"查看即时数据"}</a>:<button disabled={busy!==null||billing?.plan===plan.id} onClick={()=>void checkout(plan.id)}>{billing?.plan===plan.id?(en?"Current plan":"当前方案"):busy===plan.id?(en?"Opening checkout…":"正在打开结账页…"):(en?"Subscribe securely":"安全订阅")}</button>}</article>)}</section><section className="billingTrust"><div><b>{en?"Secure hosted checkout":"安全托管结账"}</b><p>{en?"Payment details are collected by Stripe Checkout and are not stored by Pledge Radar.":"支付信息由 Stripe Checkout 收集，质押雷达不保存银行卡数据。"}</p></div><div><b>{en?"Evidence-first data":"证据优先"}</b><p>{en?"Every research record retains its filing source and document hash.":"每条研究数据保留公告来源与文件哈希。"}</p></div><div><b>{en?"No credit conclusion":"不替代授信结论"}</b><p>{en?"Signals support due diligence and do not constitute investment advice.":"信号用于尽调筛查，不构成投资建议。"}</p></div></section></main>;
}
